grafana:
  grafana.ini:
    analytics:
      check_for_updates: true
    grafana_net:
      url: "https://grafana.net"
    log:
      mode: "console"
    paths:
      data: "/var/lib/grafana/"
      logs: "/var/log/grafana"
      plugins: "/var/lib/grafana/plugins"
      provisioning: "/etc/grafana/provisioning"
    server:
      domain: "monitoring.zakamaldin.test"
      root_url: "http://monitoring.zakamaldin.test/grafana/"
